### ISSUE TITLE
RejectedExecutionException at program termination

### ISSUE THREAD

**Issue by aanno** [swiesend/secret-service#10]
I'm using your library. It works great, but upon program termination, I always encounter the following error: 

```bash
Exception in thread "DBusConnection" java.util.concurrent.RejectedExecutionException: Task org.freedesktop.dbus.connections.AbstractConnection$1@7682e526 rejected from java.util.concurrent.ThreadPoolExecutor@710fe758[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 32]
	at java.base/java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2055)
	at java.base/java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:825)
	at java.base/java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1355)
	at org.freedesktop.dbus.connections.AbstractConnection.sendMessage(AbstractConnection.java:317)
	at org.freedesktop.dbus.connections.AbstractConnection.handleMessage(AbstractConnection.java:959)
	at org.freedesktop.dbus.connections.AbstractConnection.handleMessage(AbstractConnection.java:619)
	at org.freedesktop.dbus.connections.IncomingMessageThread.run(IncomingMessageThread.java:43)
```
I looked into this a bit and suspect that it is caused by the following refence chain: `SimpleCollection -> TransportEncryption -> DBusConnection`. If `SimpleCollection.close()` is called, `DBusConnection.close()` is _not_ called. 

Code like the following for `SimpleCollection.close()` would fix the problem:

```java
    @Override
    public void close() {
        clear();
        if (encryption != null) {
            encryption.close();
        }
        if (encrypted != null) {
            encrypted.close();
        }
        if (session != null) {
            session.close();
        }
    }
```

**Comment by swiesend** [comment]
I am still undecided, but maybe it would even be better to let the `TransportEncryption` close the session instead of the `SimpleCollection`.
