### ISSUE TITLE
DBusConnection - broken pipe

### ISSUE THREAD

**Issue by swiesend** [swiesend/secret-service#20]
There are problems with the [1.2.0](https://github.com/swiesend/secret-service/pull/19) version on shutting down.

```
[DBus Sender Thread-1] INFO org.freedesktop.dbus.connections.impl.DBusConnection - Setting reply to MethodCall(0,42) { Path=>/org/freedesktop/DBus, Interface=>org.freedesktop.DBus, Member=>RemoveMatch, Destination=>org.freedesktop.DBus, Signature=>s } { type='signal',member='CollectionChanged',interface='org.freedesktop.Secret.Service' } as an error
[Thread-2] ERROR org.freedesktop.secret.handlers.SignalHandler - org.freedesktop.dbus.exceptions.DBusException: org.freedesktop.dbus.exceptions.DBusExecutionException: Message Failed to Send: Datenübergabe unterbrochen (broken pipe)
org.freedesktop.dbus.exceptions.DBusExecutionException: Message Failed to Send: Datenübergabe unterbrochen (broken pipe)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.freedesktop.dbus.errors.Error.getException(Error.java:157)
	at org.freedesktop.dbus.errors.Error.throwException(Error.java:187)
	at org.freedesktop.dbus.RemoteInvocationHandler.executeRemoteMethod(RemoteInvocationHandler.java:164)
	at org.freedesktop.dbus.RemoteInvocationHandler.invoke(RemoteInvocationHandler.java:228)
	at com.sun.proxy.$Proxy26.RemoveMatch(Unknown Source)
	at org.freedesktop.dbus.connections.impl.DBusConnection.removeSigHandler(DBusConnection.java:818)
	at org.freedesktop.dbus.connections.AbstractConnection.removeSigHandler(AbstractConnection.java:400)
	at org.freedesktop.secret.handlers.SignalHandler.disconnect(SignalHandler.java:63)
	at org.freedesktop.secret.handlers.SignalHandler.lambda$new$0(SignalHandler.java:31)
	at java.base/java.lang.Thread.run(Thread.java:834)
[Thread-2] ERROR org.freedesktop.secret.handlers.SignalHandler - Could not remove all signal handlers from the D-Bus.
```

**Comment by swiesend** [comment]
And there is also:
```

[Thread-2] ERROR org.freedesktop.secret.handlers.SignalHandler - java.util.concurrent.RejectedExecutionException: Task org.freedesktop.dbus.connections.AbstractConnection$1@5b44a31c rejected from java.util.concurrent.ThreadPoolExecutor@2f01c4f[Shutting down, pool size = 1, active threads = 0, queued tasks = 0, completed tasks = 26]
[Thread-2] ERROR org.freedesktop.secret.handlers.SignalHandler - Could not remove all signal handlers from the D-Bus.
```
