### ISSUE TITLE
Log thrown exceptions instead of exception cause

### ISSUE THREAD

**Issue by jmehrens** [swiesend/secret-service#24]
The SimpleCollection uses exception catch pattern of:
`log.error(e.toString(), e.getCause());
 throw new IOException(e.toString(), e.getCause());`

This pattern drops the important cause frames which are needed for troubleshooting.  Currently the logging code produces the following output:
`[02 Nov 2020 18:45:33,310] [ERROR] SimpleCollection.<init>() - java.lang.NullPointerException`

This is because `e.getCause()` is null therefore, no throwable was passed to the logger.

However, if I change the catch pattern to the following:
`log.error(e.toString(), e);
 throw new IOException(e.toString(), e);`

The following is output is shown:
`[03 Nov 2020 16:34:08,347] [ERROR] SimpleCollection.<init>() - java.lang.NullPointerException
java.lang.NullPointerException: null
at org.freedesktop.secret.handlers.MessageHandler.send(MessageHandler.java:50) ~[secret-service-1.2.1.jar:?]
at org.freedesktop.secret.handlers.Messaging.send(Messaging.java:37) ~[secret-service-1.2.1.jar:?]
at org.freedesktop.secret.Service.openSession(Service.java:29) ~[secret-service-1.2.1.jar:?]
at org.freedesktop.secret.TransportEncryption.openSession(TransportEncryption.java:80) ~[secret-service-1.2.1.jar:?]
at org.freedesktop.secret.simple.SimpleCollection.init(SimpleCollection.java:174) ~[secret-service-1.2.1.jar:?]
at org.freedesktop.secret.simple.SimpleCollection.<init>(SimpleCollection.java:92) [secret-service-1.2.1.jar:?]`

Recommendation would be to:
1. Change the logging throwable arguments (right hand side) to log the root exception and not the cause.
2. Change the wrapping exception to wrap the caught exception instead of wrapping a cause that may not be present.
3. Update the logging message (left hand side) to include context about the operation that failed and avoid logging e.toString() as the message.

**Comment by swiesend** [comment]
Thank you @jmehrens for improving the code quality here a lot!

1. and 2.) I followed your recommendations and now I log and throw with with the root exception.
3.) I added better logging messages

Feel free to point further rubbish, if you see one!

I released the changes for this and #25 in version `1.2.2`.
