### ISSUE TITLE
Logger NPE in MessageHandler.send

### ISSUE THREAD

**Issue by jmehrens** [swiesend/secret-service#25]
MessageHandler logging fails to check for a null response when logging a trace message at line 50:
https://github.com/swiesend/secret-service/blob/master/src/main/java/org/freedesktop/secret/handlers/MessageHandler.java#L50

Error message with fixed logging is:
`[03 Nov 2020 16:34:08,347] [ERROR] SimpleCollection.<init>() - java.lang.NullPointerException
java.lang.NullPointerException: null
at org.freedesktop.secret.handlers.MessageHandler.send(MessageHandler.java:50) ~[secret-service-1.2.1.jar:?]
at org.freedesktop.secret.handlers.Messaging.send(Messaging.java:37) ~[secret-service-1.2.1.jar:?]
at org.freedesktop.secret.Service.openSession(Service.java:29) ~[secret-service-1.2.1.jar:?]
at org.freedesktop.secret.TransportEncryption.openSession(TransportEncryption.java:80) ~[secret-service-1.2.1.jar:?]
at org.freedesktop.secret.simple.SimpleCollection.init(SimpleCollection.java:174) ~[secret-service-1.2.1.jar:?]
at org.freedesktop.secret.simple.SimpleCollection.<init>(SimpleCollection.java:92) [secret-service-1.2.1.jar:?]
`

The code is:
`log.trace(response.toString());`

It should be changed to:
`log.trace(String.valueOf(response));`

Perhaps a logging guard statement should be added.

**Comment by swiesend** [comment]
1. `String.valueOf(response)` is much better.
2. I introduced a trace logging guard to avoid the "costly" `String.valueOf(response)`.

I released the changes for this issue and #24 in version `1.2.2`.

Feel tree to point out further issues, that concern you!
