### ISSUE TITLE
NullPointerException on systems without `gnome-keyring` installed or `login` as default collection

### ISSUE THREAD

**Issue by swiesend** [swiesend/secret-service#6]
On systems without `gnome-keyring` installed the `secret-service` can't find any default collection `/org/freedesktop/secrets/collection/login`.

This problem relates to [Cryptomator #950](https://github.com/cryptomator/cryptomator/issues/950).

[cryptomator0.log](https://github.com/swiesend/secret-service/files/3501579/cryptomator0.log)
```
18:31:24.707 [JavaFX Application Thread] ERROR o.f.secret.handlers.MessageHandler - org.freedesktop.dbus.exceptions.DBusException: org.freedesktop.DBus.Error.UnknownMethod: Keine derartige Schnittstelle »org.freedesktop.DBus.Properties« des Objekts im Pfad /org/freedesktop/secrets/collection/login
....
Caused by: java.lang.NullPointerException: null
	at org.freedesktop.secret.handlers.MessageHandler.getProperty(MessageHandler.java:72)
	at org.freedesktop.secret.handlers.Messaging.getProperty(Messaging.java:41)
	at org.freedesktop.secret.Collection.isLocked(Collection.java:86)
	at org.freedesktop.secret.simple.SimpleCollection.unlock(SimpleCollection.java:174)
	at org.freedesktop.secret.simple.SimpleCollection.<init>(SimpleCollection.java:47)
```

## Suggested solution

`MessageHandler.send()` should not return `null`, but preferably raise an `Exception`. The high low and level API should be adapted to handle this, where the high level API may return `Optional`s where returning a type or pass through any Exception as `IOException` when not returning anything.

https://github.com/swiesend/secret-service/blob/ae40b5ffaa9853db68651710cc23b5cb865ec009/src/main/java/org/freedesktop/secret/handlers/MessageHandler.java#L33-L67

**Comment by swiesend** [comment]
The [`MessageHandler`](https://github.com/swiesend/secret-service/blob/3015f6417b03050f48309bda7602d5925549d7e6/src/main/java/org/freedesktop/secret/handlers/MessageHandler.java) is updated and does not consume connection problems. Instead it throws any occurring exception as `DBusException`. This change led to an unfortunate [big commit](https://github.com/swiesend/secret-service/commit/3015f6417b03050f48309bda7602d5925549d7e6), but was inevitable in order to not commit non compiling code. I ran the test on my machine (`Ubuntu 18.04 GNOME`), but still have to test how the library behaves on other systems with and without `gnome-keyring` installed. I guess I should provide a small sample application or build Cryptomator with the current changes.

Now the high-level [`SimpleCollection`](https://github.com/swiesend/secret-service/blob/3015f6417b03050f48309bda7602d5925549d7e6/src/main/java/org/freedesktop/secret/simple/SimpleCollection.java) API consumes and logs occuring `DBusException`s and explains connection problems by throwing `IOExceptions` with a short message.

Most returning methods of the `SimpleCollection` return now an `Optional`, except of `getLabel()` and `getSecret()`. If there is no security concern to wrap the `char[]` of getSecret() as Optional, then it may be more consistent to let all returning functions return an `Optional`.
